name: Lecocq_etal_2020_SCIENCE
channels:
  - conda-forge
dependencies:
  - python =3.7
  - obspy >=1.2.0
  - matplotlib <3.2  # some issue with matplotlib.cbook.dedent need to resolve later
  - basemap >=1.3.0
  - pandas
  - seaborn
  - tqdm
  - pillow

# exact environment as of 2020-07-24:
# packages in environment at /srv/conda/envs/notebook:
# #
# # Name                    Version                   Build  Channel
# _libgcc_mutex             0.1                 conda_forge    conda-forge
# _openmp_mutex             4.5                       0_gnu    conda-forge
# alembic                   1.4.2              pyh9f0ad1d_0    conda-forge
# async_generator           1.10                       py_0    conda-forge
# attrs                     19.3.0                     py_0    conda-forge
# backcall                  0.1.0                      py_0    conda-forge
# basemap                   1.3.0            py37h17ca249_2    conda-forge
# bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
# blinker                   1.4                        py_1    conda-forge
# brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
# ca-certificates           2020.6.20            hecda079_0    conda-forge
# certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
# certipy                   0.1.3                      py_0    conda-forge
# cffi                      1.14.0           py37hd463f26_0    conda-forge
# chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
# cryptography              2.9.2            py37hb09aad4_0    conda-forge
# cycler                    0.10.0                     py_2    conda-forge
# dbus                      1.13.6               he372182_0    conda-forge
# decorator                 4.4.2                      py_0    conda-forge
# defusedxml                0.6.0                      py_0    conda-forge
# entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
# expat                     2.2.9                he1b5a44_2    conda-forge
# fontconfig                2.13.1            h86ecdb6_1001    conda-forge
# freetype                  2.10.2               he06d7ca_0    conda-forge
# future                    0.18.2           py37hc8dfbb8_1    conda-forge
# geos                      3.8.1                he1b5a44_0    conda-forge
# gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
# glib                      2.65.0               h6f030ca_0    conda-forge
# gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
# gstreamer                 1.14.5               h36ae1b5_2    conda-forge
# icu                       64.2                 he1b5a44_1    conda-forge
# idna                      2.9                        py_1    conda-forge
# importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
# importlib_metadata        1.6.0                         0    conda-forge
# ipykernel                 5.3.0            py37h43977f1_0    conda-forge
# ipython                   7.15.0           py37hc8dfbb8_0    conda-forge
# ipython_genutils          0.2.0                      py_1    conda-forge
# ipywidgets                7.5.1                      py_0    conda-forge
# jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
# jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
# jpeg                      9d                   h516909a_0    conda-forge
# json5                     0.9.0                      py_0    conda-forge
# jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
# jupyter-offlinenotebook   0.1.0                    pypi_0    pypi
# jupyter_client            6.1.3                      py_0    conda-forge
# jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
# jupyter_telemetry         0.0.5                      py_0    conda-forge
# jupyterhub-base           1.1.0                    py37_2    conda-forge
# jupyterhub-singleuser     1.1.0                    py37_2    conda-forge
# jupyterlab                1.2.6                      py_0    conda-forge
# jupyterlab_server         1.1.5                      py_0    conda-forge
# kiwisolver                1.2.0            py37h99015e2_0    conda-forge
# krb5                      1.17.1               h2fd8d38_0    conda-forge
# lcms2                     2.11                 hbd6801e_0    conda-forge
# ld_impl_linux-64          2.34                 h53a641e_4    conda-forge/label/broken
# libblas                   3.8.0               17_openblas    conda-forge
# libcblas                  3.8.0               17_openblas    conda-forge
# libcurl                   7.69.1               hf7181ac_0    conda-forge
# libedit                   3.1.20191231         h46ee950_0    conda-forge
# libffi                    3.2.1             he1b5a44_1007    conda-forge
# libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
# libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
# libgomp                   9.2.0                h24d8f2e_2    conda-forge
# libiconv                  1.15              h516909a_1006    conda-forge
# liblapack                 3.8.0               17_openblas    conda-forge
# libopenblas               0.3.10          pthreads_hb3c22a3_3    conda-forge
# libpng                    1.6.37               hed695b0_1    conda-forge
# libsodium                 1.0.17               h516909a_0    conda-forge
# libssh2                   1.9.0                hab1572f_2    conda-forge
# libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
# libtiff                   4.1.0                hc7e4089_6    conda-forge
# libuuid                   2.32.1            h14c3975_1000    conda-forge
# libwebp-base              1.1.0                h516909a_3    conda-forge
# libxcb                    1.13              h14c3975_1002    conda-forge
# libxml2                   2.9.10               hee79883_0    conda-forge
# libxslt                   1.1.33               h31b3aaa_0    conda-forge
# lxml                      4.5.2            py37he3881c9_0    conda-forge
# lz4-c                     1.9.2                he1b5a44_1    conda-forge
# mako                      1.1.0                      py_0    conda-forge
# markupsafe                1.1.1            py37h8f50634_1    conda-forge
# matplotlib                3.1.3                    py37_0    conda-forge
# matplotlib-base           3.1.3            py37h250f245_0    conda-forge
# mistune                   0.8.4           py37h8f50634_1001    conda-forge
# nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
# nbformat                  5.0.6                      py_0    conda-forge
# nbresuse                  0.3.3                      py_0    conda-forge
# ncurses                   6.1               hf484d3e_1002    conda-forge
# notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
# nteract_on_jupyter        2.1.3                      py_0    conda-forge
# numpy                     1.19.1           py37h8960a57_0    conda-forge
# oauthlib                  3.0.1                      py_0    conda-forge
# obspy                     1.2.2            py37h03ebfcd_0    conda-forge
# olefile                   0.46                       py_0    conda-forge
# openssl                   1.1.1g               h516909a_0    conda-forge
# packaging                 20.4               pyh9f0ad1d_0    conda-forge
# pamela                    1.0.0                      py_0    conda-forge
# pandas                    1.0.5            py37h0da4684_0    conda-forge
# pandoc                    2.9.2.1                       0    conda-forge
# pandocfilters             1.4.2                      py_1    conda-forge
# parso                     0.7.0              pyh9f0ad1d_0    conda-forge
# patsy                     0.5.1                      py_0    conda-forge
# pcre                      8.44                 he1b5a44_0    conda-forge
# pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
# pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
# pillow                    7.2.0            py37h718be6c_1    conda-forge
# pip                       20.1.1                     py_1    conda-forge
# proj                      7.0.0                h966b41f_4    conda-forge
# prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
# prompt-toolkit            3.0.5                      py_0    conda-forge
# psutil                    5.7.0            py37h8f50634_1    conda-forge
# pthread-stubs             0.4               h14c3975_1001    conda-forge
# ptyprocess                0.6.0                   py_1001    conda-forge
# pycparser                 2.20                       py_0    conda-forge
# pycurl                    7.43.0.5         py37h16ce93b_0    conda-forge
# pygments                  2.6.1                      py_0    conda-forge
# pyjwt                     1.7.1                      py_0    conda-forge
# pyopenssl                 19.1.0                     py_1    conda-forge
# pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
# pyproj                    2.6.1.post1      py37h34dd122_0    conda-forge
# pyqt                      5.9.2            py37hcca6a23_4    conda-forge
# pyrsistent                0.16.0           py37h8f50634_0    conda-forge
# pyshp                     2.1.0                      py_0    conda-forge
# pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
# python                    3.7.8           h6f2ec95_0_cpython    conda-forge
# python-dateutil           2.8.1                      py_0    conda-forge
# python-editor             1.0.4                      py_0    conda-forge
# python-json-logger        0.1.11                     py_0    conda-forge
# python_abi                3.7                     1_cp37m    conda-forge
# pytz                      2020.1             pyh9f0ad1d_0    conda-forge
# pyzmq                     19.0.1           py37hac76be4_0    conda-forge
# qt                        5.9.7                h0c104cb_3    conda-forge
# readline                  8.0                  hf8c457e_0    conda-forge
# requests                  2.23.0             pyh8c360ce_2    conda-forge
# ruamel.yaml               0.16.6           py37h8f50634_1    conda-forge
# ruamel.yaml.clib          0.2.0            py37h8f50634_1    conda-forge
# scipy                     1.5.1            py37ha3d9a3c_0    conda-forge
# seaborn                   0.10.1                        1    conda-forge
# seaborn-base              0.10.1                     py_1    conda-forge
# send2trash                1.5.0                      py_0    conda-forge
# setuptools                47.1.1           py37hc8dfbb8_0    conda-forge
# sip                       4.19.8          py37hf484d3e_1000    conda-forge
# six                       1.15.0             pyh9f0ad1d_0    conda-forge
# sqlalchemy                1.3.17           py37h8f50634_0    conda-forge
# sqlite                    3.32.3               hcee41ef_1    conda-forge
# statsmodels               0.11.1           py37h8f50634_2    conda-forge
# terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
# testpath                  0.4.4                      py_0    conda-forge
# tk                        8.6.10               hed695b0_0    conda-forge
# tornado                   6.0.4            py37h8f50634_1    conda-forge
# tqdm                      4.48.0             pyh9f0ad1d_0    conda-forge
# traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
# urllib3                   1.25.9                     py_0    conda-forge
# wcwidth                   0.2.3              pyh9f0ad1d_0    conda-forge
# webencodings              0.5.1                      py_1    conda-forge
# wheel                     0.34.2                     py_1    conda-forge
# widgetsnbextension        3.5.1                    py37_0    conda-forge
# xorg-libxau               1.0.9                h14c3975_0    conda-forge
# xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
# xz                        5.2.5                h516909a_0    conda-forge
# zeromq                    4.3.2                he1b5a44_2    conda-forge
# zipp                      3.1.0                      py_0    conda-forge
# zlib                      1.2.11            h516909a_1006    conda-forge
# zstd                      1.4.5                h6597ccf_1    conda-forge
