name: Lecocq_etal_2020_SCIENCE
channels:
  - conda-forge
dependencies:
  - python =3.7
  - obspy >=1.2.0
  - matplotlib <3.2  # some issue with matplotlib.cbook.dedent need to resolve later
  - basemap >=1.3.0
  - pandas
  - seaborn
  - tqdm
